name: smart_usb
description: A cross-platform (Android/Windows/macOS/Linux) USB plugin for Flutter
version: 0.4.3
homepage: https://github.com/chuvanhoang888/smart_usb
repository: https://github.com/chuvanhoang888/smart_usb

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2
  ffi: ^2.0.1
  libusb_new: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    implements: smart_usb
    platforms:
      android:
        package: com.example.smart_usb
        pluginClass: SmartUsbPlugin
        dartPluginClass: SmartUsbAndroid
      windows:
        dartPluginClass: SmartUsbWindows
        ffiPlugin: true
      macos:
        dartPluginClass: SmartUsbMacos
        ffiPlugin: true
      linux:
        dartPluginClass: SmartUsbLinux
        ffiPlugin: true
